/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.nio.file.Files;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.BufferedReader;
import java.io.IOException;

public class App {
    public static void main(String[] args) {
        System.out.println(FileReader("gates.js"));
    }

    public static String FileReader (String pathfile){
        Path path = Paths.get(pathfile);

        BufferedReader linereader = null;
        try {
            linereader = Files.newBufferedReader(path);
            String line = linereader.readLine();
            int counter = 0;
            String finall = "";
            while(line != null){
                counter++;
                int length = line.length();
                if(length != 0 && !line.substring(length - 1).equals(";") && !line.substring(length - 1).equals("}") && !line.substring(length - 1).equals("{") && !line.contains("if") && !line.contains("else")) {
                    finall += "Line" +counter+": Missing semicolon."+"\n";
                }
                line = linereader.readLine();
            }
            return finall;
        } catch (IOException ex){
            ex.printStackTrace();
            return "error";
        } finally {
            if(linereader != null) {
                try {
                    linereader.close();
                } catch(IOException e){
                    System.out.println("error at closing");
                }
            }
        }
    }
}